### ISSUE TITLE
Test about jolly is wrong.

### ISSUE THREAD

**Issue by brunoscopelliti** [brunoscopelliti/risk-card-combination#1]
It should be: 1 jolly + 2 equal cards.

**Comment by AleAntonellis** [comment]
Pushing to https://AleAntonellis@github.com/brunoscopelliti/risk-card-combination.git
remote: Permission to brunoscopelliti/risk-card-combination.git denied to AleAntonellis.
fatal: unable to access 'https://AleAntonellis@github.com/brunoscopelliti/risk-card-combination.git/': The requested URL returned error: 403

**Comment by AleAntonellis** [comment]
Risolto, quando faccio clone da source tree mi mette un URL con la mia utenza all'inizio, quando pusho non va bene :)

**Comment by AleAntonellis** [comment]
Test corretti https://github.com/brunoscopelliti/risk-card-combination/commit/fc61914999e54f7ecb33c0c9c74dbcde3ea98395
